<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net7.0-tizen</TargetFrameworks> -->
		<OutputType>Exe</OutputType>
		<RootNamespace>GuessWho</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- Display name -->
		<ApplicationTitle>GuessWho</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.guesswho</ApplicationId>
		<ApplicationIdGuid>07bf7682-335d-4b88-9906-e43e1d082fae</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">13.1</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net7.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	</PropertyGroup>
	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />

		<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.100" />
		
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="7.0.0" />
		<PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
		<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.7" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Models\" />
	  <None Remove="Resources\Images\" />
	  <None Remove="Resources\Images\ArianaGrande.jpg" />
	  <None Remove="Resources\Images\JenniferLawrence.jpg" />
	  <None Remove="Resources\Images\OliviaRodrigo.jpg" />
	  <None Remove="Resources\Images\ScarlettJohansson.jpg" />
	  <None Remove="Resources\Images\TomHiddleston.jpg" />
	  <None Remove="Resources\Images\selena_gomez.jpg" />
	  <None Remove="Resources\Images\david_beckham.jpg" />
	  <None Remove="Resources\Images\zac_efron.jpg" />
	  <None Remove="Resources\Images\ryan_renolds.jpg" />
	  <None Remove="Resources\Images\chris_pine.jpg" />
	  <None Remove="Resources\Images\renee_rapp.jpg" />
	  <None Remove="Resources\Images\brad_pitt.jpg" />
	  <None Remove="Resources\Images\ryan_gosling.jpg" />
	  <None Remove="Resources\Images\julia_roberts.jpg" />
	  <None Remove="Resources\Images\emma_stone.jpg" />
	  <None Remove="Resources\Images\jennifer_lopez.jpg" />
	  <None Remove="Resources\Images\lady_gaga.jpg" />
	  <None Remove="Resources\Images\adam_sandler.jpg" />
	  <None Remove="Resources\Images\johnny_depp.jpg" />
	  <None Remove="Resources\Images\britney_spears.jpg" />
	  <None Remove="Resources\Images\angelina_jolie.jpg" />
	  <None Remove="Resources\Images\will_smith.jpg" />
	  <None Remove="Resources\Images\ariana_grande.jpg" />
	  <None Remove="Resources\Images\jennifer_lawrence.jpg" />
	  <None Remove="Resources\Images\olivia_rodrigo.jpg" />
	  <None Remove="Resources\Images\scarlett_johansson.jpg" />
	  <None Remove="Resources\Images\tom_hiddleston.jpg" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Models\" />
	  <Folder Include="Resources\Images\" />
	</ItemGroup>
	<ItemGroup>
	  <MauiImage Include="Resources\Images\adam_sandler.jpg" />
	  <MauiImage Include="Resources\Images\britney_spears.jpg" />
	  <MauiImage Include="Resources\Images\angelina_jolie.jpg" />
	  <MauiImage Include="Resources\Images\ariana_grande.jpg" />
	  <MauiImage Include="Resources\Images\brad_pitt.jpg" />
	  <MauiImage Include="Resources\Images\chris_pine.jpg" />
	  <MauiImage Include="Resources\Images\david_beckham.jpg" />
	  <MauiImage Include="Resources\Images\emma_stone.jpg" />
	  <MauiImage Include="Resources\Images\jennifer_lawrence.jpg" />
	  <MauiImage Include="Resources\Images\jennifer_lopez.jpg" />
	  <MauiImage Include="Resources\Images\johnny_depp.jpg" />
	  <MauiImage Include="Resources\Images\julia_roberts.jpg" />
	  <MauiImage Include="Resources\Images\lady_gaga.jpg" />
	  <MauiImage Include="Resources\Images\olivia_rodrigo.jpg" />
	  <MauiImage Include="Resources\Images\renee_rapp.jpg" />
	  <MauiImage Include="Resources\Images\ryan_gosling.jpg" />
	  <MauiImage Include="Resources\Images\ryan_renolds.jpg" />
	  <MauiImage Include="Resources\Images\scarlett_johansson.jpg" />
	  <MauiImage Include="Resources\Images\selena_gomez.jpg" />
	  <MauiImage Include="Resources\Images\tom_hiddleston.jpg" />
	  <MauiImage Include="Resources\Images\will_smith.jpg" />
	  <MauiImage Include="Resources\Images\zac_efron.jpg" />
	</ItemGroup>
</Project>
